unit frmrep;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls, Buttons, ComCtrls, DB, ZAbstractRODataset,
  ZAbstractDataset, ZDataset, ppDB, ppDBPipe, ppComm, ppRelatv, ppProd,
  ppClass, ppReport, ppCtrls, ppPrnabl, ppBands, ppCache, myChkBox,
  ppStrtch, ppMemo, ppParameter, jpeg;

type
  Tfrmrepin = class(TForm)
    bt_salir: TBitBtn;
    Label1: TLabel;
    Label2: TLabel;
    BitBtn1: TBitBtn;
    fecha1: TDateTimePicker;
    fecha2: TDateTimePicker;
    dataem: TDataSource;
    pprepo: TppReport;
    pprep: TppDBPipeline;
    ppHeaderBand1: TppHeaderBand;
    ppDetailBand1: TppDetailBand;
    ppFooterBand1: TppFooterBand;
    ppImage1: TppImage;
    ppLabel1: TppLabel;
    ppShape1: TppShape;
    ppShape2: TppShape;
    ppShape3: TppShape;
    ppShape4: TppShape;
    ppShape5: TppShape;
    ppLabel2: TppLabel;
    ppLabel3: TppLabel;
    ppLabel4: TppLabel;
    ppShape6: TppShape;
    ppLabel5: TppLabel;
    ppLabel6: TppLabel;
    ppDBText3: TppDBText;
    ppShape7: TppShape;
    ck_in: TmyCheckBox;
    pping: TppLabel;
    pprein: TppLabel;
    ck_re: TmyCheckBox;
    ppcar: TppLabel;
    ck_ca: TmyCheckBox;
    pptras: TppLabel;
    ck_tr: TmyCheckBox;
    ppasc: TppLabel;
    ck_as: TmyCheckBox;
    ppcla: TppLabel;
    ck_cl: TmyCheckBox;
    pplib: TppLabel;
    ck_li: TmyCheckBox;
    ppsus: TppLabel;
    ck_su: TmyCheckBox;
    ppmh: TppLabel;
    ck_mo: TmyCheckBox;
    ppegr: TppLabel;
    ck_eg: TmyCheckBox;
    ppmdc: TppLabel;
    ck_mc: TmyCheckBox;
    ppShape8: TppShape;
    ppLabel18: TppLabel;
    ppShape9: TppShape;
    ppShape10: TppShape;
    ppShape11: TppShape;
    ppLabel19: TppLabel;
    ppLabel20: TppLabel;
    ppShape12: TppShape;
    ppShape13: TppShape;
    ppShape14: TppShape;
    ppDBText4: TppDBText;
    ppDBText6: TppDBText;
    ppLabel22: TppLabel;
    ppShape15: TppShape;
    ppShape16: TppShape;
    ppShape17: TppShape;
    ppShape18: TppShape;
    ppShape19: TppShape;
    ppLabel23: TppLabel;
    ppLabel24: TppLabel;
    ppLabel25: TppLabel;
    ppLabel26: TppLabel;
    ppShape20: TppShape;
    ppShape21: TppShape;
    ppShape22: TppShape;
    ppShape23: TppShape;
    ppDBText5: TppDBText;
    ck_ma: TmyCheckBox;
    ppmas: TppLabel;
    ppfem: TppLabel;
    ck_fe: TmyCheckBox;
    ck_so: TmyCheckBox;
    ppsol: TppLabel;
    ppviu: TppLabel;
    ck_vi: TmyCheckBox;
    ppcas: TppLabel;
    ck_cas: TmyCheckBox;
    ppdivo: TppLabel;
    ck_di: TmyCheckBox;
    ppmae: TppLabel;
    ppoti: TppLabel;
    pplic: TppLabel;
    pptsu: TppLabel;
    ck_tsu: TmyCheckBox;
    ck_lic: TmyCheckBox;
    ck_mae: TmyCheckBox;
    ck_oti: TmyCheckBox;
    ppShape24: TppShape;
    ppShape25: TppShape;
    ppLabel37: TppLabel;
    ppShape26: TppShape;
    ppShape27: TppShape;
    ppLabel38: TppLabel;
    ppDBText8: TppDBText;
    ppLabel39: TppLabel;
    ppShape28: TppShape;
    ppShape29: TppShape;
    ppShape30: TppShape;
    ppShape31: TppShape;
    ppLabel40: TppLabel;
    ppLabel41: TppLabel;
    ppLabel42: TppLabel;
    ppLabel43: TppLabel;
    ppShape32: TppShape;
    ppShape33: TppShape;
    ppShape34: TppShape;
    ppShape35: TppShape;
    ppShape36: TppShape;
    ppShape37: TppShape;
    ppShape38: TppShape;
    ppShape39: TppShape;
    ppShape40: TppShape;
    ppShape41: TppShape;
    ppShape42: TppShape;
    ppShape43: TppShape;
    ppShape44: TppShape;
    ppShape45: TppShape;
    ppShape46: TppShape;
    ppShape47: TppShape;
    ppShape48: TppShape;
    ppShape49: TppShape;
    ppDBText7: TppDBText;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppDBText13: TppDBText;
    ppDBText14: TppDBText;
    ppDBText15: TppDBText;
    ppDBText16: TppDBText;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppDBText20: TppDBText;
    ppDBText21: TppDBText;
    ppDBText22: TppDBText;
    ppLabel44: TppLabel;
    ppShape50: TppShape;
    ppShape51: TppShape;
    ppShape52: TppShape;
    ppShape53: TppShape;
    ppShape54: TppShape;
    ppShape55: TppShape;
    ppLabel45: TppLabel;
    ppLabel46: TppLabel;
    ppLabel47: TppLabel;
    ppLabel48: TppLabel;
    ppLabel49: TppLabel;
    ppLabel50: TppLabel;
    ppShape56: TppShape;
    ppShape57: TppShape;
    ppShape59: TppShape;
    ppShape60: TppShape;
    ppShape61: TppShape;
    ppDBText23: TppDBText;
    ppDBText24: TppDBText;
    ppShape58: TppShape;
    ppfij: TppLabel;
    ck_fij: TmyCheckBox;
    ck_int: TmyCheckBox;
    ppint: TppLabel;
    ppLabel55: TppLabel;
    ppLabel56: TppLabel;
    ppLabel57: TppLabel;
    ppDBText25: TppDBText;
    ppDBText26: TppDBText;
    ppDBText27: TppDBText;
    ppdt: TppLabel;
    ck_tit: TmyCheckBox;
    ck_disp: TmyCheckBox;
    ppdi: TppLabel;
    ppdipc: TppLabel;
    ck_dipc: TmyCheckBox;
    ck_hv: TmyCheckBox;
    ppdhv: TppLabel;
    ppnt: TppLabel;
    ck_ntit: TmyCheckBox;
    ck_nisp: TmyCheckBox;
    ppnin: TppLabel;
    ppnipc: TppLabel;
    ck_nipc: TmyCheckBox;
    ppShape62: TppShape;
    ppShape63: TppShape;
    ppLabel53: TppLabel;
    ppDBText28: TppDBText;
    ppShape64: TppShape;
    ppShape65: TppShape;
    ppDBText29: TppDBText;
    ppLabel54: TppLabel;
    ppLabel65: TppLabel;
    ppDBText30: TppDBText;
    ppShape66: TppShape;
    ppShape67: TppShape;
    ppShape68: TppShape;
    ppShape69: TppShape;
    ppLabel66: TppLabel;
    ppLabel67: TppLabel;
    ppDBText31: TppDBText;
    ppDBText32: TppDBText;
    ppShape70: TppShape;
    ppLabel68: TppLabel;
    ppbsi: TppLabel;
    ck_bs: TmyCheckBox;
    ppbno: TppLabel;
    ck_bn: TmyCheckBox;
    ppLabel71: TppLabel;
    ppShape71: TppShape;
    ppShape72: TppShape;
    ppShape73: TppShape;
    ppDBText33: TppDBText;
    ppLabel72: TppLabel;
    ppLabel73: TppLabel;
    cod_ban: TppDBText;
    ppShape74: TppShape;
    ppLabel74: TppLabel;
    ppShape75: TppShape;
    ppaho: TppLabel;
    ck_aho: TmyCheckBox;
    ppcor: TppLabel;
    ck_cor: TmyCheckBox;
    ppShape76: TppShape;
    ppLabel77: TppLabel;
    ppShape77: TppShape;
    ppDBText35: TppDBText;
    ppLabel78: TppLabel;
    ppShape78: TppShape;
    ppDBText36: TppDBText;
    ppLabel79: TppLabel;
    ppShape79: TppShape;
    ppLabel80: TppLabel;
    ppLabel81: TppLabel;
    ppShape81: TppShape;
    ppDBText37: TppDBText;
    ppShape82: TppShape;
    ppShape83: TppShape;
    ppLabel82: TppLabel;
    ppShape84: TppShape;
    ppDBText39: TppDBText;
    ppShape85: TppShape;
    ppLabel83: TppLabel;
    ppShape86: TppShape;
    ppDBText40: TppDBText;
    ppShape87: TppShape;
    ppLabel84: TppLabel;
    ppShape88: TppShape;
    ppDBText41: TppDBText;
    ppShape90: TppShape;
    ppShape91: TppShape;
    ppLabel86: TppLabel;
    ppShape92: TppShape;
    ppDBText43: TppDBText;
    ppShape93: TppShape;
    ppShape94: TppShape;
    ppShape95: TppShape;
    ppShape96: TppShape;
    ppShape97: TppShape;
    ppShape98: TppShape;
    ppShape99: TppShape;
    ppShape100: TppShape;
    ppLabel87: TppLabel;
    ppLabel88: TppLabel;
    ppLabel89: TppLabel;
    ppLabel90: TppLabel;
    ppMemo1: TppMemo;
    ppMemo2: TppMemo;
    ppMemo3: TppMemo;
    ppMemo4: TppMemo;
    ppMemo5: TppMemo;
    ppDBText44: TppDBText;
    ppShape101: TppShape;
    con_em: TZReadOnlyQuery;
    ppDBText45: TppDBText;
    ppShape102: TppShape;
    ctm: TComboBox;
    Label3: TLabel;
    ppParameterList1: TppParameterList;
    ppShape103: TppShape;
    ppLabel8: TppLabel;
    ppLabel9: TppLabel;
    ppLabel10: TppLabel;
    ppLabel11: TppLabel;
    ppLabel12: TppLabel;
    ppLabel13: TppLabel;
    ppLabel14: TppLabel;
    ppLabel15: TppLabel;
    ppLabel16: TppLabel;
    ppLabel17: TppLabel;
    ppLabel27: TppLabel;
    ppLabel28: TppLabel;
    ppLabel29: TppLabel;
    ppLabel30: TppLabel;
    ppLabel31: TppLabel;
    ppLabel32: TppLabel;
    ppLabel33: TppLabel;
    ppLabel34: TppLabel;
    ppLabel35: TppLabel;
    ppLabel36: TppLabel;
    ppLine1: TppLine;
    ppLine2: TppLine;
    ppLine3: TppLine;
    ppLabel51: TppLabel;
    ppLabel52: TppLabel;
    ppLabel58: TppLabel;
    ppLabel59: TppLabel;
    ppLabel60: TppLabel;
    ppLabel61: TppLabel;
    ppLabel62: TppLabel;
    ppLabel63: TppLabel;
    ppLabel64: TppLabel;
    ppLabel69: TppLabel;
    ppLabel70: TppLabel;
    ppLabel85: TppLabel;
    ppShape105: TppShape;
    ppShape106: TppShape;
    ppDBText2: TppDBText;
    ppShape107: TppShape;
    ppDBText1: TppDBText;
    ppShape108: TppShape;
    ppShape109: TppShape;
    ppShape110: TppShape;
    ppShape80: TppShape;
    ppLabel7: TppLabel;
    ck_md: TmyCheckBox;
    ppmdp: TppLabel;
    con_tit: TZReadOnlyQuery;
    datatit: TDataSource;
    reptit: TppReport;
    ppHeaderBand2: TppHeaderBand;
    ppShape89: TppShape;
    ppImage2: TppImage;
    ppShape112: TppShape;
    ppLabel75: TppLabel;
    ppDetailBand2: TppDetailBand;
    ppShape113: TppShape;
    ppShape117: TppShape;
    ppShape120: TppShape;
    ppShape121: TppShape;
    ppShape122: TppShape;
    ppShape123: TppShape;
    ppShape124: TppShape;
    ppShape125: TppShape;
    ppShape126: TppShape;
    ppShape127: TppShape;
    ppShape128: TppShape;
    ppShape129: TppShape;
    ppShape130: TppShape;
    ppShape131: TppShape;
    ppShape134: TppShape;
    ppShape135: TppShape;
    ppLabel76: TppLabel;
    ppLabel91: TppLabel;
    ppLabel92: TppLabel;
    ppDBText34: TppDBText;
    myCheckBox1: TmyCheckBox;
    ppLabel93: TppLabel;
    myCheckBox2: TmyCheckBox;
    ppLabel96: TppLabel;
    myCheckBox5: TmyCheckBox;
    myCheckBox6: TmyCheckBox;
    ppLabel99: TppLabel;
    ppLabel101: TppLabel;
    myCheckBox9: TmyCheckBox;
    ppLabel102: TppLabel;
    myCheckBox10: TmyCheckBox;
    ppLabel103: TppLabel;
    ppLabel104: TppLabel;
    ppShape137: TppShape;
    ppLabel106: TppLabel;
    ppShape138: TppShape;
    ppShape140: TppShape;
    ppDBText38: TppDBText;
    ppDBText46: TppDBText;
    ppLabel107: TppLabel;
    ppShape141: TppShape;
    ppLabel108: TppLabel;
    ppShape145: TppShape;
    ppDBText47: TppDBText;
    ppShape152: TppShape;
    ppLabel123: TppLabel;
    ppLabel124: TppLabel;
    ppShape153: TppShape;
    ppShape154: TppShape;
    ppShape155: TppShape;
    ppShape156: TppShape;
    ppLabel125: TppLabel;
    ppLabel126: TppLabel;
    ppLabel127: TppLabel;
    ppLabel128: TppLabel;
    ppShape157: TppShape;
    ppShape158: TppShape;
    ppShape159: TppShape;
    ppShape160: TppShape;
    ppShape161: TppShape;
    ppShape162: TppShape;
    ppShape163: TppShape;
    ppShape164: TppShape;
    ppShape165: TppShape;
    ppShape166: TppShape;
    ppShape167: TppShape;
    ppShape168: TppShape;
    ppShape169: TppShape;
    ppShape170: TppShape;
    ppShape171: TppShape;
    ppShape172: TppShape;
    ppShape173: TppShape;
    ppShape174: TppShape;
    ppDBText49: TppDBText;
    ppDBText50: TppDBText;
    ppDBText51: TppDBText;
    ppDBText52: TppDBText;
    ppDBText53: TppDBText;
    ppDBText54: TppDBText;
    ppDBText55: TppDBText;
    ppDBText56: TppDBText;
    ppDBText57: TppDBText;
    ppDBText58: TppDBText;
    ppDBText59: TppDBText;
    ppDBText60: TppDBText;
    ppDBText61: TppDBText;
    ppDBText62: TppDBText;
    ppDBText63: TppDBText;
    ppLabel129: TppLabel;
    ppShape175: TppShape;
    ppShape176: TppShape;
    ppShape177: TppShape;
    ppShape178: TppShape;
    ppLabel130: TppLabel;
    ppLabel131: TppLabel;
    ppLabel132: TppLabel;
    ppLabel133: TppLabel;
    ppShape181: TppShape;
    ppShape182: TppShape;
    ppShape183: TppShape;
    ppDBText64: TppDBText;
    ppDBText65: TppDBText;
    ppShape186: TppShape;
    ppLabel136: TppLabel;
    myCheckBox22: TmyCheckBox;
    ppDBText66: TppDBText;
    ppShape187: TppShape;
    ppShape188: TppShape;
    ppLabel148: TppLabel;
    ppDBText69: TppDBText;
    ppShape189: TppShape;
    ppShape190: TppShape;
    ppDBText70: TppDBText;
    ppLabel149: TppLabel;
    ppLabel150: TppLabel;
    ppDBText71: TppDBText;
    ppShape191: TppShape;
    ppShape192: TppShape;
    ppShape193: TppShape;
    ppShape194: TppShape;
    ppLabel151: TppLabel;
    ppLabel152: TppLabel;
    ppDBText72: TppDBText;
    ppDBText73: TppDBText;
    ppLabel164: TppLabel;
    ppShape199: TppShape;
    ppLabel165: TppLabel;
    ppShape200: TppShape;
    ppShape201: TppShape;
    ppLabel166: TppLabel;
    ppLabel167: TppLabel;
    ppShape202: TppShape;
    ppLabel168: TppLabel;
    ppShape203: TppShape;
    ppShape204: TppShape;
    ppLabel169: TppLabel;
    ppShape205: TppShape;
    ppDBText83: TppDBText;
    ppShape207: TppShape;
    ppShape208: TppShape;
    ppShape209: TppShape;
    ppLabel171: TppLabel;
    ppLabel172: TppLabel;
    ppLabel173: TppLabel;
    ppMemo7: TppMemo;
    ppMemo8: TppMemo;
    ppMemo9: TppMemo;
    ppShape214: TppShape;
    ppLabel174: TppLabel;
    ppLabel194: TppLabel;
    ppLabel195: TppLabel;
    ppLabel198: TppLabel;
    ppLabel199: TppLabel;
    ppLabel202: TppLabel;
    ppLabel203: TppLabel;
    ppLabel205: TppLabel;
    ppDBText86: TppDBText;
    ppShape215: TppShape;
    ppDBText87: TppDBText;
    ppShape216: TppShape;
    ppLabel206: TppLabel;
    ppLabel207: TppLabel;
    ppFooterBand2: TppFooterBand;
    ppParameterList2: TppParameterList;
    ppDBPipeline1: TppDBPipeline;
    ppLabel21: TppLabel;
    ppShape151: TppShape;
    ppDBText48: TppDBText;
    ppDBMemo1: TppDBMemo;
    ppLabel94: TppLabel;
    ppLabel95: TppLabel;
    ppLabel97: TppLabel;
    ppLabel98: TppLabel;
    ppLabel100: TppLabel;
    ppDBText42: TppDBMemo;
    procedure bt_salirClick(Sender: TObject);
    procedure BitBtn1Click(Sender: TObject);
    procedure FormShow(Sender: TObject);
    procedure ppDetailBand1BeforePrint(Sender: TObject);
    procedure ppDBText5Print(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frmrepin: Tfrmrepin;

implementation

uses frmacces;

{$R *.dfm}

procedure Tfrmrepin.bt_salirClick(Sender: TObject);
begin
  close;
end;

procedure Tfrmrepin.BitBtn1Click(Sender: TObject);
begin
if ctm.Text='TITULARIDAD' then
begin
   con_tit.Close;
   con_tit.Params[0].AsDate:=fecha1.Date;
   con_tit.Params[1].AsDate:=fecha2.Date;
   con_tit.Open;
   reptit.Print;
end
else
begin
   con_em.Close;
   con_em.Params[0].AsDate:=fecha1.Date;
   con_em.Params[1].AsDate:=fecha2.Date;
   con_em.Params[2].AsString:=ctm.Text;
   con_em.Open;
   pprepo.Print;
end;
end;

procedure Tfrmrepin.FormShow(Sender: TObject);
begin

fecha1.Date:=date;
fecha2.Date:=date;

end;

procedure Tfrmrepin.ppDetailBand1BeforePrint(Sender: TObject);
begin
  //*****************************
  if ctm.Text<>'TITULARIDAD' then
  begin
     if con_em.FieldByName('tipomov').AsString='INGRESO' then ck_in.Checked:=true else ck_in.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='REINGRESO'then ck_re.Checked:=true else ck_re.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='CARGO ADICIONAL'then ck_ca.Checked:=true else ck_ca.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='TRASLADO'then ck_tr.Checked:=true else ck_tr.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='ASCENSO' then ck_as.Checked:=true else ck_as.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='CLASIFICACION' then ck_cl.Checked:=true else ck_cl.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='LIBERACION DE CARGO' then ck_li.Checked:=true else ck_li.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='SUSPENCION' then ck_su.Checked:=true else ck_su.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='MODIFICACION DE HORAS' then ck_mo.Checked:=true else ck_mo.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='EGRESOS' then ck_eg.Checked:=true else ck_eg.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='MODIFICACION DE CARGO' then ck_mc.Checked:=true else ck_mc.Checked:=false;
     if con_em.FieldByName('tipomov').AsString='MODIFICACION DE DATOS PERSONALES' then ck_md.Checked:=true else ck_md.Checked:=false;

     if con_em.FieldByName('sexo').AsString='MASCULINO' then ck_ma.Checked:=true else ck_ma.Checked:=false;
     if con_em.FieldByName('sexo').AsString='FEMENINO'  then ck_fe.Checked:=true else ck_fe.Checked:=false;

     if con_em.FieldByName('edo_civil').AsString='SOLTERO' then ck_so.Checked:=true else ck_so.Checked:=false;
     if con_em.FieldByName('edo_civil').AsString='CASADO' then ck_cas.Checked:=true else ck_cas.Checked:=false;
     if con_em.FieldByName('edo_civil').AsString='VIUDO' then ck_vi.Checked:=true else ck_vi.Checked:=false;
     if con_em.FieldByName('edo_civil').AsString='DIVORCIADO' then ck_di.Checked:=true else ck_di.Checked:=false;

     if con_em.FieldByName('nivel_aca').AsString='LIC. O PROF.' then  ck_lic.Checked:=true else ck_lic.Checked:=false;
     if con_em.FieldByName('nivel_aca').AsString='MAESTRO' then  ck_mae.Checked:=true else ck_mae.Checked:=false;
     if con_em.FieldByName('nivel_aca').AsString='T.S.U. EDUCACION' then  ck_tsu.Checked:=true else ck_tsu.Checked:=false;
     if con_em.FieldByName('nivel_aca').AsString='OTRO TITULO' then  ck_oti.Checked:=true else ck_oti.Checked:=false;

     if con_em.FieldByName('tipo_nombr').AsString='FIJO' then  ck_fij.Checked:=true else ck_fij.Checked:=false;
     if con_em.FieldByName('tipo_nombr').AsString='INTERINO' then  ck_int.Checked:=true else ck_int.Checked:=false;

     if con_em.FieldByName('t_diurno').AsString='TITULAR' then  ck_tit.Checked:=true else ck_tit.Checked:=false;
     if con_em.FieldByName('t_diurno').AsString='INTERINO (S/P)' then  ck_disp.Checked:=true else ck_disp.Checked:=false;
     if con_em.FieldByName('t_diurno').AsString='INTERINO(P/CONCURSO)' then  ck_dipc.Checked:=true else ck_dipc.Checked:=false;
     if con_em.FieldByName('t_diurno').AsString='HORAS VARIABLES' then  ck_hv.Checked:=true else ck_hv.Checked:=false;

     if con_em.FieldByName('t_nocturno').AsString='TITULAR' then  ck_ntit.Checked:=true else ck_ntit.Checked:=false;
     if con_em.FieldByName('t_nocturno').AsString='INTERINO (S/P)' then  ck_nisp.Checked:=true else ck_nisp.Checked:=false;
     if con_em.FieldByName('t_nocturno').AsString='INTERINO(P/CONCURSO)' then  ck_nipc.Checked:=true else ck_nipc.Checked:=false;

     if con_em.FieldByName('bb').AsString='SI' then  ck_bs.Checked:=true else ck_bs.Checked:=false;
     if con_em.FieldByName('bb').AsString='NO' then  ck_bn.Checked:=true else ck_bn.Checked:=false;

     if con_em.FieldByName('tipo_cuenta').AsString='CORRIENTE' then  ck_cor.Checked:=true else ck_cor.Checked:=false;
     if con_em.FieldByName('tipo_cuenta').AsString='AHORRO' then  ck_aho.Checked:=true else ck_aho.Checked:=false;
   end;
    //*****************************

end;

procedure Tfrmrepin.ppDBText5Print(Sender: TObject);
begin
if ck_in.Checked=true then
   ppdbtext5.Visible:=true
else
   ppdbtext5.Visible:=false;
end;

end.
